# Generated by Django 5.0.6 on 2025-06-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0002_user_application'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='application',
            table='applications',
        ),
        migrations.AlterModelTable(
            name='document',
            table='documents',
        ),
        migrations.AlterModelTable(
            name='ipo',
            table='ipos',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
